/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_cc_ccjni_Hellojni */

#ifndef _Included_com_example_cc_ccjni_Hellojni
#define _Included_com_example_cc_ccjni_Hellojni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_cc_ccjni_Hellojni
 * Method:    cc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_cc_ccjni_Hellojni_cc
  (JNIEnv *, jobject);

/*
 * Class:     com_example_cc_ccjni_Hellojni
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_cc_ccjnis_Hellojni_sum
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_cc_ccjni_Hellojni
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_cc_ccjni_Hellojni_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
